// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDahghDaRoh7t0vy4wvhMZ3MuA1c_vuw40',
    appId: '1:567546430323:android:6af34ceadbc925aedb7b06',
    messagingSenderId: '567546430323',
    projectId: 'talkify-74f7e',
    storageBucket: 'talkify-74f7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSVjDIZu2kQJXhV_dN8NN46js9evDTyas',
    appId: '1:567546430323:ios:9c77300475832420db7b06',
    messagingSenderId: '567546430323',
    projectId: 'talkify-74f7e',
    storageBucket: 'talkify-74f7e.appspot.com',
    androidClientId: '567546430323-saald88ggoj1npq2fq7kuvaqh8a56f59.apps.googleusercontent.com',
    iosClientId: '567546430323-3lkc2oonrkehl3qiba8pv06bnia3ln6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkify',
  );
}
